---
- name: Monitor /etc/passwd file for changes
  hosts: localhost

  sources:
    - ansible.builtin.filesystem:
        paths:
          - /etc/passwd
        state: modified
  rules:
    - name: Check /etc/passwd changes
      condition: event.source == 'filesystem' and event.state == 'modified'
      action:
        run_job_template:
          name: User and Group Password File Restore
          organization: Default